/* eslint-disable import/prefer-default-export */
export const dummyData = {
    "version": "4.26.9",
    "system": {
      "manufacturer": "LENOVO",
      "model": "80ES",
      "version": "Lenovo B50-30",
      "serial": "CB35865163",
      "uuid": "4A9FEEE8-48ED-E411-A26A-F0761CAF252A",
      "sku": "LENOVO_BI_IDEAPAD9C_BU_idea_FM_Lenovo B50-30"
    },
    "bios": {
      "vendor": "LENOVO",
      "version": "LENOVO - 1",
      "releaseDate": "2014-11-26",
      "revision": ""
    },
    "baseboard": {
      "manufacturer": "LENOVO",
      "model": "Lenovo B50-30",
      "version": "31900058WIN",
      "serial": "CB35865163",
      "assetTag": ""
    },
    "chassis": {
      "manufacturer": "LENOVO",
      "model": "",
      "type": "Notebook",
      "version": "Lenovo B50-30",
      "serial": "CB35865163",
      "assetTag": "",
      "sku": ""
    },
    "os": {
      "platform": "win32",
      "distro": "Microsoft Windows 10 Home",
      "release": "10.0.18363",
      "codename": "",
      "kernel": "10.0.18363",
      "arch": "x64",
      "hostname": "Dadaist",
      "codepage": " 437",
      "logofile": "windows",
      "serial": "00326-10000-00000-AA456",
      "build": "18363",
      "servicepack": "0.0",
      "uefi": false
    },
    "uuid": {
      "os": "ba8e12b6-b136-481b-a712-4cc530517210"
    },
    "versions": {
      "kernel": "10.0.18363",
      "openssl": "1.1.0",
      "systemOpenssl": "1.1.1d",
      "systemOpensslLib": "OpenSSL",
      "node": "12.0.0",
      "v8": "7.3.492.27-electron.0",
      "npm": "6.12.0",
      "yarn": "1.19.1",
      "pm2": "",
      "gulp": "",
      "grunt": "1.3.2",
      "git": "2.24.1.windows.2",
      "tsc": "",
      "mysql": "",
      "redis": "",
      "mongodb": "",
      "apache": "",
      "nginx": "",
      "php": "",
      "docker": "",
      "postfix": "",
      "postgresql": "",
      "perl": "5.26.2",
      "python": "3.8.3",
      "python3": "",
      "pip": "19.2.3",
      "pip3": "19.2.3",
      "java": "",
      "gcc": "",
      "virtualbox": "",
      "dotnet": ""
    },
    "cpu": {
      "manufacturer": "Intel®",
      "brand": "Celeron® N2840",
      "vendor": "GenuineIntel",
      "family": "6",
      "model": "55",
      "stepping": "8",
      "revision": "14088",
      "voltage": "",
      "speed": "2.16",
      "speedmin": "",
      "speedmax": "2.16",
      "governor": "",
      "cores": 2,
      "physicalCores": 2,
      "processors": 1,
      "socket": "None",
      "cache": {
        "l1d": 0,
        "l1i": 0,
        "l2": 1048576,
        "l3": 0
      },
      "flags": "de msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe"
    },
    "graphics": {
      "controllers": [
        {
          "vendor": "Intel Corporation",
          "model": "Intel(R) HD Graphics",
          "bus": "PCI",
          "vram": 2112,
          "vramDynamic": true
        }
      ],
      "displays": [
        {
          "vendor": "(Standard monitor types)",
          "model": "Generic PnP Monitor",
          "main": true,
          "builtin": true,
          "connection": "INTERNAL",
          "resolutionx": 1366,
          "resolutiony": 768,
          "sizex": 34,
          "sizey": 19,
          "pixeldepth": 32,
          "currentResX": 1366,
          "currentResY": 768,
          "positionX": 0,
          "positionY": 0,
          "currentRefreshRate": 60
        }
      ]
    },
    "net": [
      {
        "iface": "Cellular 4",
        "ifaceName": "HUAWEI Mobile Connect - 3G Network Card #5",
        "ip4": "10.232.234.61",
        "ip4subnet": "255.255.255.252",
        "ip6": "",
        "ip6subnet": "",
        "mac": "00:1e:10:1f:f7:1c",
        "internal": false,
        "virtual": false,
        "operstate": "up",
        "type": "wireless",
        "duplex": "",
        "mtu": "",
        "speed": 28.8,
        "dhcp": "false",
        "dnsSuffix": "",
        "ieee8021xAuth": "Not defined",
        "ieee8021xState": "Disabled",
        "carrierChanges": 0
      },
      {
        "iface": "Loopback Pseudo-Interface 1",
        "ifaceName": "Loopback Pseudo-Interface 1",
        "ip4": "127.0.0.1",
        "ip4subnet": "255.0.0.0",
        "ip6": "::1",
        "ip6subnet": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "mac": "00:00:00:00:00:00",
        "internal": true,
        "virtual": false,
        "operstate": "down",
        "type": "",
        "duplex": "",
        "mtu": "",
        "speed": -1,
        "dhcp": false,
        "dnsSuffix": "",
        "ieee8021xAuth": "Not defined",
        "ieee8021xState": "Disabled",
        "carrierChanges": 0
      },
      {
        "iface": "Broadcom 802.11n Network Adapter",
        "ifaceName": "Broadcom 802.11n Network Adapter",
        "ip4": "",
        "ip4subnet": "",
        "ip6": "",
        "ip6subnet": "",
        "mac": "ac:d1:b8:f0:d6:61",
        "virtual": false,
        "operstate": "down",
        "type": "wireless",
        "duplex": "",
        "mtu": "",
        "speed": 9223372036854.775,
        "dhcp": "true",
        "dnsSuffix": "",
        "ieee8021xAuth": "Not defined",
        "ieee8021xState": "Disabled",
        "carrierChanges": 0
      },
      {
        "iface": "Realtek PCIe GBE Family Controller",
        "ifaceName": "Realtek PCIe GBE Family Controller",
        "ip4": "",
        "ip4subnet": "",
        "ip6": "",
        "ip6subnet": "",
        "mac": "f0:76:1c:af:25:2a",
        "virtual": false,
        "operstate": "down",
        "type": "wired",
        "duplex": "",
        "mtu": "",
        "speed": 9223372036854.775,
        "dhcp": "true",
        "dnsSuffix": "",
        "ieee8021xAuth": "Not defined",
        "ieee8021xState": "Disabled",
        "carrierChanges": 0
      }
    ],
    "memLayout": [
      {
        "size": 4294967296,
        "bank": "BANK 0",
        "type": "DDR3",
        "clockSpeed": 1333,
        "formFactor": "SODIMM",
        "manufacturer": "Samsung",
        "partNum": "M471B5173DB0-YK0",
        "serialNum": "15235420",
        "voltageConfigured": 0,
        "voltageMin": 0,
        "voltageMax": 0
      },
      {
        "size": 4294967296,
        "bank": "BANK 1",
        "type": "DDR3",
        "clockSpeed": 1333,
        "formFactor": "SODIMM",
        "manufacturer": "Kingston",
        "partNum": "9905417-067.A00G",
        "serialNum": "17541114",
        "voltageConfigured": 0,
        "voltageMin": 0,
        "voltageMax": 0
      }
    ],
    "diskLayout": [
      {
        "device": "",
        "type": "HD",
        "name": "ST500LT012-1DG142",
        "vendor": "(Standard disk drives)",
        "size": 500105249280,
        "bytesPerSector": 512,
        "totalCylinders": 60801,
        "totalHeads": 255,
        "totalSectors": 976768065,
        "totalTracks": 15504255,
        "tracksPerCylinder": 255,
        "sectorsPerTrack": 63,
        "firmwareRevision": "0002LVM1",
        "serialNum": "W3PG9Q57",
        "interfaceType": "SATA",
        "smartStatus": "Ok"
      }
    ]
  }
